### ISSUE TITLE
--path contant not working

### ISSUE THREAD

**Issue by khromov** [danielbachhuber/dictator#52]
I was setting up a new site with Dictator and for some reason the `--path` flag does not seem to be working.

```
➜  wp git:(master) ✗ wp dictator export site site-state.yml --path=public
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

But just moving into the public folder works fine:

```
➜  wp git:(master) ✗ cd public 
➜  public git:(master) ✗ wp dictator export site site-state.yml              
Success: State written to file.
```

Running OSX, PHP 7.0.20 via Brew, latest master of Dictator `5151f24` (although 0.1 is not working either.)

Any ideas?

**Comment by danielbachhuber** [comment]
No ideas, sorry. Dictator doesn't do anything special with `--path=<path>`, so it may be something else in your configuration.
