### ISSUE TITLE
Is this still being supported?

### ISSUE THREAD

**Issue by cneiman** [danielbachhuber/dictator#53]
Hey! 

Looking to use this in a prod environment and am just wondering if this is still being maintained and if it is still in use. 

Thanks!

**Comment by danielbachhuber** [comment]
Thanks for the issue, @cneiman.

I'm not actively developing Dictator at the moment. I think some people are using it in production, but I'm not certain. I haven't seen many new issues opened, so that's either a sign that's it's stable, or not much in use.
