### ISSUE TITLE
Started a fork

### ISSUE THREAD

**Issue by jenkoian** [danielbachhuber/dictator#61]
Hi!

As per https://github.com/danielbachhuber/dictator/pull/60#issuecomment-749619911 we (the company I work for) have created a fork in order to get fixes and things we need in place. You can see the initial changes we've made from the latest version of this repo here: https://github.com/danielbachhuber/dictator/compare/master...boxuk:master

We've given you attribution and would be more than willing to contribute these back to this repo should you pick up the reigns on this again, just let us know and I'll open up the PR.

So just wanted to drop a note to let you know, if the project has indeed fallen into abandonment, it might be cool to [mark it as so in composer](https://getcomposer.org/doc/04-schema.md#abandoned) - you can suggest our fork as an alternative if you so wish.

Thanks for making this, it really fills a need we have and we're excited about working on it over the coming months. Finally, all the best with whatever you're focussing your time on now 👍

**Comment by danielbachhuber** [comment]
Hey @jenkoian,

Works for me! I've:

1. Added `"abandoned"` to `composer.json`.
2. Added a note to `README.md`.

I'll archive this repo shortly.

Good luck!
